language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls manage.py test

after_script:
  - coveralls

#before_deploy: "echo 'Deploying polls from Travis...'"
# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: "AKIAS5SQ2OCZ2PMFPEWG"
#   secret_access_key:
#     secure: "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"
#   region: "us-west-2"
#   app: "polls"
#   env: "django-env"
#   bucket_name: "polls-S3"

# only_create_app_version: "true"